// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shopping.Models;

#nullable disable

namespace Shopping.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20230706152919_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("Shopping.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Express Galaxy Tumbler",
                            Price = 19.95m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aero Life Air Purifier",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ocean Wave Projector",
                            Price = 29.95m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Illuminated Globe Decor",
                            Price = 42.50m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Moonlight Cushion",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sunrise Alarm Clock",
                            Price = 35.00m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Frosty Mini Fridge",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Breeze Tower Fan",
                            Price = 75.89m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Comet Electric Scooter",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Starlight Projector",
                            Price = 27.50m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
